# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Andy B.
title: IS Audit | Data Protection | Investigation | Information Security | Applied Data Science
# email: https://www.linkedin.com/in/buserandre/
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: 
github_username: busera
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: buserandre
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: "@data-and-science"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000
# medium_username: "@buser.andre"

# Additional icon links
additional_links:
- title: Medium
  icon: fab fa-medium
  url: https://medium.com/@buser.andre
- title: Kaggle
  icon: fab fa-kaggle
  url: https://www.kaggle.com/busera

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile1.jpg
about_content: | # this will include new lines to allow paragraphs
  Leveraging extensive experience in Internal Audit, Information Systems Auditing, Security, and Investigation, coupled with a Master of Applied Data Science from the University of Michigan, I aim to enhance organizational risk management and control processes while serving as a trusted advisor to the business. My focus is on applying advanced analytics and AI within Internal Audit and GRC frameworks, emphasizing Data Ethics and Responsible AI. I am passionate about driving digital transformation in audit practices, ensuring robust governance in the evolving technology landscape, and supporting strategic business decisions through insightful audit findings and recommendations.

content:
  - title: DS and ML Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Readability Optimizer
        caption: May 2020 - Present
        link: github.com/busera/proto__readability_optimizer
        link_text: github.com
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/busera/mads__decode_dementia
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Originally developed in my free time to practice Python, Readability Optimizer is a prototype tool designed to help authors improve the readability of their texts.
        description: | # this will include new lines to allow paragraphs
          This project marked one of my first endeavors in preparation for my upcoming Master's in Applied Data Science (MADS) at the University of Michigan.

          This prototype served as the foundation for an in-house solution, particularly for internal audit reports. This solution was expanded to import the audit report and analyze all observation paragraphs for readability.

          The tool employs various readability tests and analyses to provide insights and suggestions for enhancing text clarity and comprehension, thereby improving written communication in professional settings.

          **Next step is to implement a local LLM to provide more text improvements recommendations.**

      - layout: left
        border: weak
        title: Decode Dementia
        caption: Oct 2023 - Dec 2023
        link: github.com/busera/mads__decode_dementia
        link_text: github.com
        quote: >
          Key findings indicate that TBIs, especially those involving loss of consciousness, alongside the presence of the APOE Îµ4 allele and male gender, significantly increase dementia risk, while higher education levels seem to offer some protective effects.
        description: | # this will include new lines to allow paragraphs
          This project was designed to enhance our understanding of the outcomes following traumatic brain injuries, focusing on their determinants and consequences. We used causal inference to investigate the complex relationships between TBI and the subsequent risk of dementia, considering a range of demographic and clinical factors.
      
      - layout: left
        border: weak
        title: Predicting Text Difficulty
        caption: Oct 2022 - Dec 2022
        link: github.com/busera/mads__predicting_text_difficulty
        link_text: github.com
        quote: >
          Our analysis found that the fine-tuned Random Forest model demonstrated the highest accuracy score of 0.7544.
        description: | # this will include new lines to allow paragraphs
          This project aimed to classify sentences from articles in the "Simple English Wikipedia" to determine whether they require simplification to enhance their accessibility and comprehensibility for audiences with low reading proficiency, including students, children, and non-native English speakers. The project employed supervised and unsupervised learning techniques to extract and create features for sentence classification.
      
      - layout: left
        title: Analyze GDPR Fines
        caption: Oct 2021 - Dec 2021
        link: github.com/busera/mads__analyze_gdpr_fines
        link_text: github.com
        quote: >
          Our analysis of GDPR fines from 2018 to 2021 has revealed crucial insights for data protection practices, particularly in the healthcare sector.
        description: | # this will include new lines to allow paragraphs
          Analyzing GDPR fines imposed by the European data protection authorities could reveal the main reasons and focus areas of the authorities for non-compliance and could allow our organization to timely address similar gaps in their data privacy strategy.

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Algorithm Ossification
        sub_title: The Feedback Loop Between Algorithms and the Real World
        caption: Jul 2024
        link: https://medium.com/@buser.andre/algorithm-ossification-the-feedback-loop-between-algorithms-and-fe52ecfbf218?source=friends_link&sk=a7da82f03950e839491d34bc6aaa17b1
        link_text: medium.com
        #quote: >
        #  An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.
        description: |
          In todayâ€™s world, algorithms are a big part of our daily lives. They suggest what we should watch and help decide if we can get a loan. These computer programs make many decisions that affect us all.
          
          But what happens when these algorithms start to change the very world they are supposed to describe?
          
          This is what we call algorithm ossification, and itâ€™s important phenomenon to understand.
      
      - layout: left
        border: weak
        title: Understanding AI System Classification and Risk Assessment
        #sub_title: Explaining these concepts and how they relate to each other
        caption: Jul 2024
        link: https://medium.com/@buser.andre/understanding-ai-system-classification-and-risk-assessment-in-ai-images-tables-a5da2c1eb510?sk=bce834d52700f6741d57f27f4faf6c36
        link_text: medium.com
        #quote: >
        #  An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.
        description: |
          In the evolving field of artificial intelligence (AI) governance, two important concepts can get mixed up: AI System Classification and AI System Risk Assessment. This confusion can lead to problems in managing the related AI risks. This article aims to explain these concepts and how they relate to each other, using insights from major AI governance frameworks.

      - layout: left
        border: weak
        title: Exploring the Power of ChatGPT
        sub_title: A Comprehensive Introduction
        caption: Jun 2024
        link: "360incontrol.ch/2024/06/28/artificial-intelligence-a-comprehensive-view-ðŸ¤–/"
        link_text: 360incontrol.ch
        #quote: >
        #  An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.
        description: |
          An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.

      - layout: left
        border: weak
        title: Decomposing the Term â€œInformation Security Riskâ€
        #sub_title: A Comprehensive Introduction
        caption: Apr 2017
        link: https://www.linkedin.com/pulse/decomposing-term-information-security-risk-andr%2525C3%2525A9-buser-cisa-cissp/
        link_text: linkedin.com
        #quote: >
        #  An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.
        description: |
          This article addresses the frequently asked question "What is an (information security) risk?" from the perspective of an IS Auditor and Information Security Risk Manager. It presents three tailored explanations to accommodate varying levels of audience interest and time constraints. 
          
          The first is a concise formula, the second a comprehensive definition based on industry standards, and the third a detailed exploration using ISO 31000:2009 as a foundation. This multi-tiered approach offers flexibility in explaining information security risk across different professional contexts and audience needs.
  
      - layout: left
        #border: weak
        title: How to Write (Better) Information Security Risks
        #sub_title: A Comprehensive Introduction
        caption: Oct 2016
        link: https://www.linkedin.com/pulse/how-write-better-information-security-risks-simplified-andr%25C3%25A9-buser/?trackingId=fiWEJHVvRv8bgyNzcwoHNg
        link_text: linkedin.com
        #quote: >
        #  An overview of ChatGPT, delving into its underlying mechanisms, constraints, and practical applications.
        description: |
          During the process of risk assessment it can be challenging to differentiate between risks, threats and vulnerabilities. This is important, because based on the threats and vulnerabilities â€“ as well as on the impacted assets â€“ the mitigation controls and risk levels can be different.

          In now-a-days processes many of the risk assessment steps are starting with â€“ or including â€“ the term â€œriskâ€, although the â€œreal riskâ€ is the results of all those steps and activities. This small, but important difference, will be explained in the following sections.

  
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Novartis
        #link: novartis.com
        #link_text: boringcompany.com
        sub_title: Director | Senior Manager
        caption: Apr 2010 - Present
        quote: >
          Bridging the gap between innovation and responsible governance in the AI and data science landscape.

        description: |
          In my current role at Novartis, I support and implement data analytics initiatives and provide support to our in-house Open Source Intelligence (OSINT) and investigation teams. My role involves leveraging advanced data science techniques to enhance our global security strategies, improve risk assessment, and safeguard the company's digital assets.

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak
        title: Certified Fraud Investigator (CFE)
        sub_title: Association of Certified Fraud Examiners (ACFE)
        caption: Feb 2024
        description: |
          Holder of specialized credential demonstrating expertise in fraud detection, prevention, and investigation. Proficient in analyzing financial transactions, legal aspects of fraud, and advanced investigation techniques. Skilled in implementing anti-fraud controls and conducting internal investigations. Globally recognized for maintaining high standards of fraud examination knowledge and ethical conduct.
      - layout: left
        border: weak
        title: Certified Data Protection Officer (CDPO)
        sub_title: PECB
        caption: Feb 2019
        description: |
          Holder of specialized certification demonstrating expertise in data protection and privacy regulations. Proficient in developing and implementing data protection strategies, policies, and procedures. Skilled in conducting data protection impact assessments, managing data breaches, and ensuring organizational compliance with relevant laws such as GDPR. Recognized for ability to act as a key advisor on data protection matters and liaison between the organization, data subjects, and supervisory authorities.
      - layout: left
        border: weak
        title: Certified Information Systems Security Professional (CISSP)
        sub_title: ISC2
        caption: Jan 2016
        description: |
          Holder of advanced certification demonstrating comprehensive knowledge and expertise in information security. Proficient in designing, implementing, and managing cybersecurity programs across all eight domains of the Common Body of Knowledge (CBK). Skilled in risk management, asset security, security architecture, network security, identity and access management, security assessment, security operations, and software development security. Recognized globally for maintaining high ethical standards and continuously updating information security knowledge to address emerging threats and technologies.
      - layout: left
        #border: weak
        title: Certified Information Systems Auditor (CISA)
        sub_title: ISACA
        caption: Aug 2011
        description: |
          Holder of globally recognized certification demonstrating expertise in information systems auditing, control, and security. Proficient in conducting comprehensive IT audits, assessing vulnerabilities, and ensuring compliance with industry standards and regulations. Skilled in evaluating information systems operations, governance, and cybersecurity practices. Adept at developing and implementing risk-based IT audit strategies, reporting on audit findings, and providing valuable insights to improve organizational IT controls and processes. Committed to maintaining high professional standards and staying current with evolving technology and audit practices.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Michigan
        caption: Jan 2021 - Dec 2023
        sub_title: MSc Applied Data Science
        link: https://www.si.umich.edu/programs/master-applied-data-science
        link_text: umich.edu
        quote: >
          The University of Michigan, founded in 1817, is a top-tier public research institution known for its innovative programs and commitment to academic excellence.
        description: |
          At the University of Michigan's School of Information, I completed the Master of Applied Data Science (MADS) program, graduating in December 2023. This comprehensive program provided me with a solid foundation in key areas of data science, including machine learning, data mining, and big data analytics.

          The curriculum emphasized practical application, allowing me to work on real-world projects and develop problem-solving skills applicable to complex datasets.

          This experience equipped me with both the technical skills and ethical understanding necessary to navigate the challenges of modern data science, preparing me for impactful contributions in my professional role.


#  - title: Publications
#    layout: list
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)#
#
#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
